language: r
sudo: false
cache: packages

matrix:
  include:
  - r: oldrel
  - r: release
  - r: devel
  - os: osx
    r: release

branches:
  except:
  - dev

warnings_are_errors: true

notifications:
  email: false